"""Interactive CLI to manage config.yaml without touching code.

Usage:
    python tr_sync.py config init                   # initial wizard
    python tr_sync.py config show                   # prints config.yaml
    python tr_sync.py config validate               # checks the config
    python tr_sync.py config set KEY VALUE          # change a value (dot-notation)
    python tr_sync.py config add-asset ISIN LABEL   # add an ISIN to the portfolio
    python tr_sync.py config remove-asset ISIN      # remove an ISIN from the portfolio
    python tr_sync.py config add-ignore SECTION TXT # add a pattern to ignore_events[SECTION]
    python tr_sync.py config remove-ignore SECTION TXT
    python tr_sync.py config features               # feature toggles
"""
from __future__ import annotations

import sys
from pathlib import Path

import questionary
import yaml

CONFIG_PATH = Path(__file__).resolve().parent / "config.yaml"
EXAMPLE_PATH = Path(__file__).resolve().parent / "config.example.yaml"

# ── Helpers ───────────────────────────────────────────────────────────────


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _save_yaml(path: Path, data: dict, header: str | None = None) -> None:
    """Write `data` to `path` as readable YAML. `header` optional comment at the top."""
    text = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    if header:
        text = f"{header.rstrip()}\n\n{text}"
    path.write_text(text, encoding="utf-8")


def _set_nested(d: dict, dotted_key: str, value):
    """Set d['a']['b']['c'] = value for dotted_key='a.b.c'. Creates intermediate dicts."""
    parts = dotted_key.split(".")
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def _get_nested(d: dict, dotted_key: str, default=None):
    parts = dotted_key.split(".")
    cur = d
    for p in parts:
        if not isinstance(cur, dict) or p not in cur:
            return default
        cur = cur[p]
    return cur


def _coerce_value(s: str):
    """Convert the CLI string to a sensible type: bool/int/float/str. None and null → None."""
    if s.lower() in ("null", "none", "~"):
        return None
    if s.lower() in ("true", "yes"):
        return True
    if s.lower() in ("false", "no"):
        return False
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    return s


def _confirm_overwrite(path: Path) -> bool:
    if not path.exists():
        return True
    return questionary.confirm(
        f"{path.name} already exists. Overwrite?",
        default=False,
    ).ask() or False


# ── `init` wizard ─────────────────────────────────────────────────────────


_HEADER = """\
# tr-sync — personal config generated by `tr-sync config init`.
# Do NOT push to the public repo (it's in .gitignore).
# For a clean template with all fields documented, see config.example.yaml.
"""


def cmd_init(args):
    """Interactive wizard. Asks step by step and writes config.yaml."""
    print("\n🛠  tr-sync configuration wizard\n")

    if not _confirm_overwrite(CONFIG_PATH):
        print("Aborted.")
        return 1

    cfg: dict = {}

    # ── Sheet ID ──
    sheet_id = questionary.text(
        "ID of your Google Sheet (from the URL: docs.google.com/spreadsheets/d/<THIS_ID>/edit):",
        validate=lambda v: True if v and not v.startswith("REEMPLAZA") and not v.startswith("REPLACE") else "Paste the actual ID",
    ).ask()
    if sheet_id is None:
        return 1
    cfg["sheet_id"] = sheet_id.strip()

    # ── Features (toggles) ──
    features = questionary.checkbox(
        "Which parts of your Sheet to sync (space to toggle):",
        choices=[
            questionary.Choice("Expenses", value="expenses", checked=True),
            questionary.Choice("Income", value="income", checked=True),
            questionary.Choice("Investments (Dinero invertido YYYY)", value="investments", checked=True),
            questionary.Choice("Portfolio (Calculo ganancias)", value="portfolio", checked=True),
        ],
    ).ask()
    if features is None:
        return 1
    cfg["features"] = {k: (k in features) for k in ("expenses", "income", "investments", "portfolio")}

    # ── Tabs ──
    cfg["sheets"] = {}
    if cfg["features"]["expenses"]:
        cfg["sheets"]["expenses"] = questionary.text(
            "Name of the expenses tab:",
            default="Gastos",
        ).ask() or "Gastos"
        cfg["sheets"]["expenses_layout"] = questionary.select(
            "Layout of the expenses tab:",
            choices=[
                questionary.Choice("monthly_columns — months as column pairs (Concepto+Importe)", value="monthly_columns"),
                questionary.Choice("ledger — one row per event with Date/Concept/Amount", value="ledger"),
            ],
            default="monthly_columns",
        ).ask() or "monthly_columns"
    if cfg["features"]["income"]:
        cfg["sheets"]["income"] = questionary.text(
            "Name of the income tab:",
            default="Ingresos",
        ).ask() or "Ingresos"
        cfg["sheets"]["income_layout"] = questionary.select(
            "Layout of the income tab:",
            choices=[
                questionary.Choice("monthly_columns", value="monthly_columns"),
                questionary.Choice("ledger", value="ledger"),
            ],
            default="monthly_columns",
        ).ask() or "monthly_columns"

    if cfg["features"]["investments"]:
        cfg["sheets"]["investments_year_format"] = questionary.text(
            "Pattern for the investments tab name (must contain {year}):",
            default="Dinero invertido {year}",
            validate=lambda v: True if "{year}" in v else "Must contain {year}",
        ).ask() or "Dinero invertido {year}"

    if cfg["features"]["portfolio"]:
        cfg["sheets"]["portfolio"] = questionary.text(
            "Name of the portfolio tab:",
            default="Calculo ganancias",
        ).ask() or "Calculo ganancias"

    cfg["sheets"]["status"] = questionary.text(
        "Name of the sync-status tab (the script will create it):",
        default="Estado sync",
    ).ask() or "Estado sync"
    cfg["sheets"]["sync_state"] = questionary.text(
        "Name of the hidden internal-dedup tab:",
        default="_sync_state",
    ).ask() or "_sync_state"

    # ── Markers for the monthly_columns layout ──
    if (cfg["sheets"].get("expenses_layout") == "monthly_columns"
            or cfg["sheets"].get("income_layout") == "monthly_columns"):
        print("\nMarkers the script searches for at the end of each month to find the summary block.")
        if cfg["sheets"].get("expenses_layout") == "monthly_columns":
            markers_e = questionary.text(
                "Expenses markers (comma-separated):",
                default="gastos innecesarios, gastos totales, extraordinarios",
            ).ask() or ""
            cfg.setdefault("summary_markers", {})["expenses"] = [
                m.strip() for m in markers_e.split(",") if m.strip()
            ]
        if cfg["sheets"].get("income_layout") == "monthly_columns":
            markers_i = questionary.text(
                "Income markers (comma-separated):",
                default="ingresos totales, ingresos, totales",
            ).ask() or ""
            cfg.setdefault("summary_markers", {})["income"] = [
                m.strip() for m in markers_i.split(",") if m.strip()
            ]

    # ── Portfolio: ISIN/label/range ──
    if cfg["features"]["portfolio"]:
        print("\nLet's define the ISIN → row mapping for the Portfolio tab.")
        cfg["portfolio_value_range"] = questionary.text(
            "A1 range where current values are written (e.g. C2:C8):",
            default="C2:C8",
            validate=lambda v: True if ":" in v else "Must be an A1 range like C2:C8",
        ).ask() or "C2:C8"

        n = questionary.text(
            "How many assets are you going to track in the portfolio?",
            default="7",
            validate=lambda v: v.isdigit() and int(v) > 0 or "Positive integer",
        ).ask() or "7"
        n = int(n)

        cfg["portfolio_cell_map"] = []
        for i in range(n):
            isin = questionary.text(f"  Asset {i+1} — ISIN:").ask()
            if not isin:
                break
            label = questionary.text(f"  Asset {i+1} — Short label:").ask()
            cfg["portfolio_cell_map"].append({"isin": isin.strip(), "label": (label or isin).strip()})

    # ── Asset name map ──
    if cfg["features"]["investments"]:
        print("\nMapping of TR names to your Investments tab.")
        print("E.g. 'Core S&P 500 USD (Acc)' → 'SP 500'. Press Enter on an empty ISIN to finish.")
        amap: dict = {}
        while True:
            tr_name = questionary.text("  Name TR uses (empty to finish):").ask()
            if not tr_name:
                break
            display = questionary.text("  Name as it appears in your tab:").ask()
            if display:
                amap[tr_name.strip()] = display.strip()
        if amap:
            cfg["asset_name_map"] = amap

    # ── Crypto (optional) ──
    crypto = questionary.text(
        "Crypto ISINs in your portfolio (comma-separated, empty if none):",
        default="",
    ).ask() or ""
    crypto_list = [c.strip() for c in crypto.split(",") if c.strip()]
    if crypto_list:
        cfg["crypto_isins"] = crypto_list

    # ── Timezone and buffer ──
    cfg["timezone"] = questionary.text("Time zone:", default="Europe/Madrid").ask() or "Europe/Madrid"
    cfg["default_buffer_days"] = int(questionary.text(
        "Buffer days when downloading the month's events:",
        default="7",
        validate=lambda v: v.isdigit() and int(v) >= 0 or "Integer >= 0",
    ).ask() or "7")

    # ── Confirmation ──
    print("\n📄 Config summary:")
    print(yaml.safe_dump(cfg, allow_unicode=True, sort_keys=False))
    if not questionary.confirm("Save this config to config.yaml?", default=True).ask():
        print("Aborted, nothing was saved.")
        return 1

    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"\n✅ {CONFIG_PATH.name} saved. Run `make doctor` to verify.")
    return 0


# ── show / validate ──────────────────────────────────────────────────────


def cmd_show(args):
    if not CONFIG_PATH.exists():
        print(f"❌ {CONFIG_PATH.name} does not exist. Run `tr-sync config init` to create it.")
        return 1
    print(CONFIG_PATH.read_text(encoding="utf-8"))
    return 0


def cmd_validate(args):
    """Load the config and run the same validation tr_sync does at startup."""
    if not CONFIG_PATH.exists():
        print(f"❌ {CONFIG_PATH.name} does not exist.")
        return 1
    try:
        # Importing tr_sync already loads and validates the config; if we got
        # here, OK.
        import importlib
        import tr_sync as _tr
        importlib.reload(_tr)
        print(f"✅ {CONFIG_PATH.name} is valid.")
        return 0
    except Exception as e:
        print(f"❌ Error in config.yaml:\n{e}")
        return 1


# ── set ──────────────────────────────────────────────────────────────────


def cmd_set(args):
    """Change a config value with dot-notation: `config set sheets.expenses Gastos`."""
    if not CONFIG_PATH.exists():
        print(f"❌ {CONFIG_PATH.name} does not exist. Run `config init` first.")
        return 1
    cfg = _load_yaml(CONFIG_PATH)
    value = _coerce_value(args.value)
    _set_nested(cfg, args.key, value)
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ {args.key} = {value!r}")
    print("   Note: comments in the file are lost when the YAML is regenerated.")
    return 0


# ── portfolio: add-asset / remove-asset ──────────────────────────────────


def cmd_add_asset(args):
    cfg = _load_yaml(CONFIG_PATH)
    pcm = cfg.setdefault("portfolio_cell_map", [])
    if any(e.get("isin") == args.isin for e in pcm):
        print(f"⚠  {args.isin} is already in portfolio_cell_map.")
        return 1
    pcm.append({"isin": args.isin, "label": args.label})
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ Added {args.isin} ({args.label}). portfolio_cell_map now has {len(pcm)} entries.")
    print(f"   Remember to update `portfolio_value_range` if it was a fixed column.")
    return 0


def cmd_remove_asset(args):
    cfg = _load_yaml(CONFIG_PATH)
    pcm = cfg.get("portfolio_cell_map", [])
    new_pcm = [e for e in pcm if e.get("isin") != args.isin]
    if len(new_pcm) == len(pcm):
        print(f"⚠  {args.isin} was not in portfolio_cell_map.")
        return 1
    cfg["portfolio_cell_map"] = new_pcm
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ Removed {args.isin}. portfolio_cell_map now has {len(new_pcm)} entries.")
    return 0


# ── ignore_events: add / remove ──────────────────────────────────────────


def cmd_add_ignore(args):
    if args.section not in ("income", "expenses"):
        print("❌ section must be 'income' or 'expenses'.")
        return 1
    cfg = _load_yaml(CONFIG_PATH)
    ignore = cfg.setdefault("ignore_events", {}).setdefault(args.section, {})
    titles = ignore.setdefault("title_contains", [])
    if args.text in titles:
        print(f"⚠  '{args.text}' is already in ignore_events.{args.section}.title_contains.")
        return 1
    titles.append(args.text)
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ Added '{args.text}' to ignore_events.{args.section}.title_contains.")
    return 0


def cmd_remove_ignore(args):
    cfg = _load_yaml(CONFIG_PATH)
    titles = (cfg.get("ignore_events") or {}).get(args.section, {}).get("title_contains", [])
    if args.text not in titles:
        print(f"⚠  '{args.text}' was not in ignore_events.{args.section}.title_contains.")
        return 1
    titles.remove(args.text)
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ Removed '{args.text}'.")
    return 0


# ── features (toggles) ───────────────────────────────────────────────────


def cmd_features(args):
    cfg = _load_yaml(CONFIG_PATH)
    current = cfg.get("features") or {"expenses": True, "income": True, "investments": True, "portfolio": True}
    selected = questionary.checkbox(
        "Which features to enable:",
        choices=[
            questionary.Choice("expenses", value="expenses", checked=current.get("expenses", True)),
            questionary.Choice("income", value="income", checked=current.get("income", True)),
            questionary.Choice("investments", value="investments", checked=current.get("investments", True)),
            questionary.Choice("portfolio", value="portfolio", checked=current.get("portfolio", True)),
        ],
    ).ask()
    if selected is None:
        return 1
    cfg["features"] = {k: (k in selected) for k in ("expenses", "income", "investments", "portfolio")}
    _save_yaml(CONFIG_PATH, cfg, header=_HEADER)
    print(f"✅ Features updated: {cfg['features']}")
    return 0


# ── Dispatcher ───────────────────────────────────────────────────────────


def main(argv: list[str]) -> int:
    """Entry point for the 'config' subcommand. argv are the args after 'config'."""
    import argparse

    parser = argparse.ArgumentParser(prog="tr-sync config")
    sub = parser.add_subparsers(dest="action", required=True)

    sub.add_parser("init", help="Interactive wizard (first-time setup)")
    sub.add_parser("show", help="Print config.yaml")
    sub.add_parser("validate", help="Validate config.yaml")

    p = sub.add_parser("set", help="Change a value (dot-notation: sheets.expenses Gastos)")
    p.add_argument("key")
    p.add_argument("value")

    p = sub.add_parser("add-asset", help="Add an ISIN to portfolio_cell_map")
    p.add_argument("isin")
    p.add_argument("label")

    p = sub.add_parser("remove-asset", help="Remove an ISIN from portfolio_cell_map")
    p.add_argument("isin")

    p = sub.add_parser("add-ignore", help="Add a pattern to ignore_events[section].title_contains")
    p.add_argument("section", choices=["income", "expenses"])
    p.add_argument("text")

    p = sub.add_parser("remove-ignore", help="Remove a pattern from ignore_events[section].title_contains")
    p.add_argument("section", choices=["income", "expenses"])
    p.add_argument("text")

    sub.add_parser("features", help="Wizard to enable/disable features")

    args = parser.parse_args(argv)
    handler = {
        "init": cmd_init,
        "show": cmd_show,
        "validate": cmd_validate,
        "set": cmd_set,
        "add-asset": cmd_add_asset,
        "remove-asset": cmd_remove_asset,
        "add-ignore": cmd_add_ignore,
        "remove-ignore": cmd_remove_ignore,
        "features": cmd_features,
    }[args.action]
    return handler(args) or 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
